### ISSUE TITLE
Error when DB only has 1 resource added to it via the .add module

### ISSUE THREAD

**Issue by SalehAhmad1** [embedchain/embedchain#91] opened 2023-06-28 12:15 UTC
Hello,
I had to issue this error on embedchain during the inference that arises when there is only one resource added to the chromadb. Below is the attached screenshot to the error on streamlit app of embedchain that I created.  
![image](https://github.com/embedchain/embedchain/assets/74538266/44766237-bef8-44c1-a742-b91db5ffeb3a)

**Comment by cachho** [comment] 2023-06-28 21:05
I would merge my PR #63 first, maybe that helps, then we should investigate this.

**Comment by cachho** [comment] 2023-07-01 13:06
My last reply was non-sense, but it works for me with 1 resource.

```
from dotenv import load_dotenv
load_dotenv()

from embedchain import App

naval_chat_bot = App()

# Embed Local Resources
naval_chat_bot.add_local("qna_pair", ("Who is Naval Ravikant?", "Naval Ravikant is an Indian-American entrepreneur and investor."))

print(naval_chat_bot.query('Can you tell me who Naval Ravikant is?'))
```

From my experience, the issue is more likely that your database was deleted, take a look at my comment on #98.

**Comment by cachho** [comment] 2023-07-01 13:13
It turns out, the embedding finds the nearest vector, no matter how far it is. So even if you just have one 1 resource and you ask a completely different question, that resource is still the closest vector and is returned. 

@taranjeet this will be interesting for you too, because these questions keep popping up.

Here's an example:
```
naval_chat_bot.add_local("qna_pair", ("Who is Naval Ravikant?", "Naval Ravikant is an Indian-American entrepreneur and investor."))

print(naval_chat_bot.dry_run("What was SalehAhmad1's issue about?"))
print(naval_chat_bot.query("What was SalehAhmad1's issue about?"))
```

Obviously, the database has no answer for the query. But it still returns the following:
```
Use the following pieces of context to answer the query at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.
        Q: Who is Naval Ravikant?
A: Naval Ravikant is an Indian-American entrepreneur and investor.
        Query: What was SalehAhmad1's issue about?
        Helpful Answer:
        
I don't know.
```

So yes, it finds the response as the nearest vector even if the distance is infinite.

**Comment by cachho** [comment] 2023-07-10 14:50
All the tests the community have run since then let us suspect that the database was empty at the time you ran this. Unless you can confirm that it's not (using the count method) or a script that starts with a reset, I will close this issue for being non-reproducible.

**Closed by cachho** 2023-07-10 14:50 UTC
