### ISSUE TITLE
Discrepancy Between pip Library Version and GitHub Repository for LlmConfig Import

### ISSUE THREAD

**Issue by lianghsun** [embedchain/embedchain#560] opened 2023-09-05 10:59 UTC
### 🐛 Describe the bug

There seems to be a discrepancy between the version of the package available on the pip library and the latest version on this GitHub repository. Specifically, the `LlmConfig import from embedchain.config` is failing on the pip version, but the GitHub repository suggests it should be present.

**Reproduction of the error:**
```
from embedchain.config import LlmConfig 
```

**Expected behavior**: Successful import of LlmConfig without any errors.

**Actual behavior**:
```
Traceback (most recent call last):
  File "/home/user/Code/experiment/embedchain_play/main.py", line 6, in <module>
    from embedchain.config import LlmConfig 
ImportError: cannot import name 'LlmConfig' from 'embedchain.config' (/home/user/miniconda3/envs/embedchain/lib/python3.10/site-packages/embedchain/config/__init__.py)
```
I also noticed that the `base_llm_config.py` file seems to be missing from the llm directory in the pip library version.

I've verified that this issue hasn't been reported previously by checking both existing and past issues.

Thank you for your attention to this matter!

**Comment by cachho** [comment] 2023-09-05 14:28
Hey, yeah we're about to release a new version for this. It's in the main branch but not in pypi. Tomorrow they should be in sync.

**Comment by Panczo** [comment] 2023-09-05 21:46
Thanks @cachho for quick answer, I have the same issue right now.

**Comment by agokrani** [comment] 2023-09-06 17:01
Hi @cachho, 

I also have the same issue for now. Can you please post how to build from source? When I do pip install . in the git repo, it gives following error: 

Processing /home/aman/experiments/embedchain
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['notebooks', 'embedchain'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

and make install gives the same error as well. Do you have any guidelines?

**Comment by cachho** [comment] 2023-09-06 17:22
> I also have the same issue for now. Can you please post how to build from source?

`poetry build`

**Comment by circularmachines** [comment] 2023-09-08 05:38
Solution for n00bs like me:
pip install embedchain==0.0.53

**Comment by cachho** [comment] 2023-09-10 22:53
> Solution for n00bs like me is to install the previous version. `pip install embedchain==0.0.53`

The problem is that the docs are of the latest version. We suggest using the latest version, as it brings many fixes and easier to use apis.

**Comment by cachho** [comment] 2023-09-10 22:53
Closing this because everything is in sync now.

**Closed by cachho** 2023-09-10 22:53 UTC
Labels: bug
