### ISSUE TITLE
add support for csv

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#161] opened 2023-07-06 15:52 UTC
I have that with privateGPT already, but it's not very good with csv files and is a bit slow perhaps. Can you beat it?
- twitter: https://twitter.com/vagero4/status/1676978801383821312

**Comment by cachho** [comment] 2023-07-06 16:38
duplicate of #87

**Comment by cachho** [comment] 2023-07-10 14:25
closing with a reference to #87

**Closed by cachho** 2023-07-10 14:25 UTC
