### ISSUE TITLE
Is top_p really mandatory for hugging face hub LLMs

### ISSUE THREAD

**Issue by taranjeet** [embedchain/embedchain#1094] opened 2024-01-01 10:12 UTC
### 🐛 Describe the bug

I was trying to use an LLM from Hugging face and skipped passing top_p. Got an error saying that it must be a value between 0 and 1.

Want to validate if top_p is really needed or optional?

If its optional, then we should update our logic to allow a user to use HF without passing top_p
If its mandatory, then we should document it in the Hugging Face related docs.

Here is the relevant code snippet from `llm/huggingface.py`
```
if config.top_p > 0.0 and config.top_p < 1.0:
            model_kwargs["top_p"] = config.top_p
        else:
            raise ValueError("`top_p` must be > 0.0 and < 1.0")
```

**Comment by hossam-zaki** [comment] 2024-01-01 20:22
I also experienced this error

**Comment by ianderrington** [comment] 2024-01-03 18:26
I :+1: this comment and note that the [quickstart](https://docs.embedchain.ai/get-started/quickstart#open-source-models) doesn't work because of this error.

**Comment by taranjeet** [comment] 2024-01-03 19:11
Hey @ianderrington , thanks for the code snippet.
Just fixed the bug in https://github.com/embedchain/embedchain/pull/1110
Please try it out now and let me know if it works.

**Comment by ianderrington** [comment] 2024-01-03 19:47
I can confirm the fix works. Thanks

**Comment by Dev-Khant** [comment] 2024-06-02 09:09
Closing the issue as it is working now.

**Closed by Dev-Khant** 2024-06-02 09:09 UTC
