### ISSUE TITLE
Response Amount - Custom OpenAI Settings

### ISSUE THREAD

**Issue by Meathelix1** [embedchain/embedchain#103] opened 2023-06-30 05:00 UTC
Hello,

Is there a setting to increase the amount for the response? 

I am currently getting a very limited response. 

Would also love custom settings for OpenAI.

**Comment by cachho** [comment] 2023-07-01 12:55
You mean something like #63 ? Taking more documents into account? Or more characters?

**Comment by cachho** [comment] 2023-08-04 11:01
closing this because the issue has not been described in a way where we can work with it. Please reopen in case you can reproduce and describe the issue in the latest version.

**Closed by cachho** 2023-08-04 11:01 UTC
