### ISSUE TITLE
[BUG] Unable to instantiate model

### ISSUE THREAD

**Issue by fabianocastello** [embedchain/embedchain#166] opened 2023-07-06 17:54 UTC
I think Embedchan is promising and I am investing time to test it.
I was able to install the package in a new environment and did succeed running a small test like this:
```
from embedchain import OpenSourceApp
naval_chat_bot = OpenSourceApp()
naval_chat_bot.add("youtube_video", "https://www.youtube.com/watch?v=3qHkcs3kG44")
naval_chat_bot.add("pdf_file", "https://navalmanack.s3.amazonaws.com/Eric-Jorgenson_The-Almanack-of-Naval-Ravikant_Final.pdf")
naval_chat_bot.add("web_page", "https://nav.al/feedback")
naval_chat_bot.add("web_page", "https://nav.al/agi")
naval_chat_bot.add("pdf_file", "testCV.pdf")
naval_chat_bot.add_local("qna_pair", ("Who is Naval Ravikant?", "Naval Ravikant is an Indian-American entrepreneur and investor."))
```
**However, when I try to make a simple query like** 

```
from embedchain import OpenSourceApp
naval_chat_bot = OpenSourceApp()
print(naval_chat_bot.query("What unique capacity does Naval argue humans possess when it comes to understanding explanations or concepts?"))
```

**I got an error "Unable to instantiate model".**

I tried reinstalling everything, clear local cache and search for an answer in all repo issues. None result!

Can you please help?

I am running locally in a MacMini 16Gb M2 Pro.

**Comment by fabianocastello** [comment] 2023-07-06 18:34
You got it right: top works, bottom does not.
I am running locally and installed using "pip install  embedchain" in a brand new python env.

**Comment by nschantz21** [comment] 2023-07-06 18:55
I am having the same problem.
fresh install.
It looks like the problem is coming from `gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.dylib`

I am getting an invalid model error when trying to load any gpt4all model

Running on Apple M1 Pro, Mac OS Monterey (12.6.7).
embedchain 0.0.15
python 3.10

**Comment by fabianocastello** [comment] 2023-07-06 20:06
> I am having the same problem. fresh install. It looks like the problem is coming from `gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.dylib`
> 
> I am getting an invalid model error when trying to load any gpt4all model
> 
> Running on Apple M1 Pro, Mac OS Monterey (12.6.7). embedchain 0.0.15 python 3.10

Just FYI, I was about to run on Colab.

**Comment by cachho** [comment] 2023-07-06 20:48
passing this to @taranjeet as he worked on introducing the open source model.

**Comment by taranjeet** [comment] 2023-08-12 04:33
I tried the code just now. Its working fine.
Closing for now, feel free to reopen if the issue is still happening.

**Closed by taranjeet** 2023-08-12 04:33 UTC
Labels: bug
